### ISSUE TITLE
How to use setGlobalDiscount with Fixed amount

### ISSUE THREAD

**Issue by blkaleeb** [anayarojo/laravel-shopping-cart#15]
how can i update cart::total() with discount price ,
for example total price of 4 products equal to 1000$
i want give user 20$ discount , how can I update total price with new price (980$) ?

thank you

**Comment by blkaleeb** [comment]
I try to change the Calculation on DefaultCalculator.php but the problem is each cart was having that calculation

**Comment by anayarojo** [comment]
Hi @blkaleeb 
Currently, the package does not support global fixed discounts. But still, there are other ways to get that.

For example, if you have the following Cart:
|Item|Qty|Price|Total|
|----|----|----|----|
|Product A|5|$50|$250|
|Product B|2|$100|$200|
|Product C|1|$25|$25|
|Product D|1|$25|$25|

a) You can calculate the discount rate and set it to a `cartItem`:
```php
$discount = 20;
$calculatedDiscountRate = $discount / $item->priceTotal; // If we choose the 'Product A', we will get 0.08
$item->setDiscountRate($calculatedDiscountRate);
```

b) If you need another functionality, you can implement your `Calculator`:

```php
use Gloudemans\Shoppingcart\CartItem;
use Gloudemans\Shoppingcart\Contracts\Calculator;

class CustomCalculator implements Calculator
{
    public static function getAttribute(string $attribute, CartItem $cartItem)
    {
        $decimals = config('cart.format.decimals', 2);

        switch ($attribute) {
            case 'discountTotal':
                return round($cartItem->options['fixedDiscount'], $decimals);
        }
    }
}
```

c) Since the `Calculator` dependency is only available in `CarItem` and not in `Cart`, you can extend the `Cart` class and override the `discountFloat()` function:

```php
use Gloudemans\Shoppingcart\Cart;

class CustomCart extends Cart
{
    private $cartDiscount;

    public function setCartDiscount($value)
    {
        $this->cartDiscount= $value;
    }

    public function discountFloat()
    {
        return $this->getContent()->reduce(function ($discount, CartItem $cartItem) {
            return $discount + $cartItem->discountTotal;
        }, $this->cartDiscount);
    }
}
```
